name: 'xp-cloudflared-tunnel'
inputs:
  token:
    required: true
  password:
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - '-v ./ /www/admin/localhost_80/wwwroot'
    - ${{ inputs.token }}
    - ${{ inputs.password }}
